/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DataBase.ConnectionDB;
import Models.Record;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Graphics;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AddRecordView extends javax.swing.JFrame {

    ConnectionDB myDB = new ConnectionDB();

    /**
     * Creates new form AddRecordView
     */
    public AddRecordView() {
        initComponents();
        setLocationRelativeTo(null);
        requestNoTF.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        hospitalCB = new javax.swing.JComboBox<>();
        sectionCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        requestNoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateSpinner = new javax.swing.JSpinner();
        deviceNameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        factoryNameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        modelTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        serialNoTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        toolsTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        requestStateCB = new javax.swing.JComboBox<>();
        AddRequestBtn = new javax.swing.JButton();
        CancelRequestBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hospitalCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "مستشفى الحسين", "مستشفى الملكة رانيا العبدالله للأطفال", "مستشفى الملكة علياء العسكري", "مستشفى الأميرة هيا بنت الحسين", "مستشفى الأمير راشد بن الحسن", "مستشفى الأمير علي بن الحسين", "مستشفى الأمير زيد بن الحسين", "مستشفى الأمير هاشم بن الحسين", "مستشفى الأمير هاشم بن عبدالله الثاني", "مركز معالجة الأورام", "مركز الملكة علياء لأمراض وجراحة القلب", "مركز الامير حسين لأمراض وجراحة الكلى", "مركز الأميرة إيمان للأبحاث والعلوم المخبرية", "مركز التأهيل الملكي", "مركز طبي الحسا", "مركز طبي القويرة", "أخرى" }));

        sectionCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sectionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "العمليات", "ICU", "الطوارئ", "الأشعة", "التوليد", "الخداج", "العزل", "أخرى" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("المستشفى:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("القسم:");

        requestNoTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        requestNoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("رقم طلب الوارد:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("تاريخ الطلب:");

        dateSpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK_IN_MONTH));

        deviceNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deviceNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deviceNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceNameTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("اسم الجهاز:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("الشركة الصانعة:");

        factoryNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        factoryNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("الموديل:");

        modelTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("الرقم التسلسلي:");

        serialNoTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serialNoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serialNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNoTFActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("القطع:");

        toolsTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolsTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("حال الطلب:");

        requestStateCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        requestStateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "تم الشراء (سلفه)", "تم الشراء (ذمم)", " قطع احتياطيه", "إصلاح", "قيد الاجراء", "موافقة مديرية" }));

        AddRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-plus-25.png"))); // NOI18N
        AddRequestBtn.setText("اضافة الطلب");
        AddRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRequestBtnActionPerformed(evt);
            }
        });

        CancelRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CancelRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-25.png"))); // NOI18N
        CancelRequestBtn.setText("إلغاء الامر");
        CancelRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(deviceNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(96, 96, 96)
                        .addComponent(requestNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(factoryNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalCB, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(118, 118, 118)
                        .addComponent(sectionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(serialNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(62, 62, 62)
                        .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(toolsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addGap(129, 129, 129)
                        .addComponent(requestStateCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(CancelRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(AddRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deviceNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(factoryNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(hospitalCB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(sectionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serialNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(toolsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(requestStateCB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)))
                .addGap(106, 106, 106)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelRequestBtn)
                    .addComponent(AddRequestBtn)))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deviceNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceNameTFActionPerformed

    private void serialNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNoTFActionPerformed

    private void AddRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRequestBtnActionPerformed
        SimpleDateFormat formater = new SimpleDateFormat("yyyy/MM/dd");
        SimpleDateFormat yearFormat = new SimpleDateFormat("yyyy");
        String spinnerValue = formater.format(dateSpinner.getValue());
        String spinnerYear = yearFormat.format(dateSpinner.getValue());
        System.out.println(spinnerValue);
        Record record = new Record(requestNoTF.getText(), spinnerYear,
                hospitalCB.getSelectedItem().toString(), sectionCB.getSelectedItem().toString(),
                spinnerValue, deviceNameTF.getText(), factoryNameTF.getText(), modelTF.getText(),
                serialNoTF.getText(), toolsTF.getText(), requestStateCB.getSelectedItem().toString());
        if (myDB.addRecord(record)) {
            JOptionPane.showMessageDialog(null, "تمت اضافة الطلب بنجاح.");
            clearFeilds();
        }
    }//GEN-LAST:event_AddRequestBtnActionPerformed

    private void CancelRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRequestBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelRequestBtnActionPerformed

    public void clearFeilds() {
        requestNoTF.setText("");
        hospitalCB.setSelectedIndex(0);
        sectionCB.setSelectedIndex(0);
        deviceNameTF.setText("");
        factoryNameTF.setText("");
        modelTF.setText("");
        serialNoTF.setText("");
        toolsTF.setText("");
        requestStateCB.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRequestBtn;
    private javax.swing.JButton CancelRequestBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JTextField deviceNameTF;
    private javax.swing.JTextField factoryNameTF;
    private javax.swing.JComboBox<String> hospitalCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modelTF;
    private javax.swing.JTextField requestNoTF;
    private javax.swing.JComboBox<String> requestStateCB;
    private javax.swing.JComboBox<String> sectionCB;
    private javax.swing.JTextField serialNoTF;
    private javax.swing.JTextField toolsTF;
    // End of variables declaration//GEN-END:variables
}
